version: "3.9"
services:
  server:
    build: ./wsp
    command: ./wsp/wsp_server -config ./server.cfg
    expose:
      - 8080
    ports:
      - "127.0.0.1:8080:8080"
  client:
    build: ./wsp
    command: ./wsp/wsp_client -config ./client.cfg
  ubuntu:
    build: ./ubuntu
